# Generated by Django 3.1.4 on 2020-12-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emusii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emusii',
            name='song_id',
            field=models.CharField(default='abc', max_length=120),
            preserve_default=False,
        ),
    ]
