# Generated by Django 3.1.4 on 2021-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emusii', '0002_remove_node_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='song_id',
            field=models.CharField(default='NA', max_length=120),
            preserve_default=False,
        ),
    ]
