# Generated by Django 3.1.4 on 2020-12-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emusii', '0002_emusii_song_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emusii',
            old_name='song_id',
            new_name='emoji',
        ),
    ]
